In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1
type(arr1)

arr2 = np.array([[1,2,3,4,5],[5,4,3,2,1],[1,2,3,4,5]])
arr2

arr3 = np.zeros((2,3))
arr3

arr4 = np.ones((4,4))
arr4

arr5 = np.identity(5)
arr5

arr6 = np.arange(10)
arr6

arr7 = np.arange(5,20,2)
arr7

arr8 = np.linspace(10,30,6)
arr8

arr9 = arr8.copy()
arr9

arr10 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr10.shape
arr10.ndim

arr10.size       #number of items 
arr10.itemsize   # int = 4byte
arr10.dtype      #type like int float etc
arr10.astype('float')

# list_a = range(100)
# arr11 = np.arange(100)
# import sys
# print(sys.getsizeof(12)*len(list_a))
# print(arr11.itemsize * arr11.size)

# import time
# x = range(10000000)
# y = range(10000000,20000000)
# start_time = time.time()
# z = [(x,y) for x,y in zip(x,y)]
# print((time.time() - start_time)) 

# a = np.arange(10000000)
# b = np.arange(10000000,20000000)
# start_time = time.time()
# c = a+b
# print((time.time() - start_time)) 

arr12 = np.arange(24).reshape(6,4)
arr12

arr12
arr12[:,2]         # to print columns of a matrix
arr12[:,1:3]        #to print 2nd and 3rd column of every row
# arr12[3:4,1:3]      #to print 2nd and 3rd column of 4th row
arr12[4:6,2:4]      #to print 3rd and 4th column of 5th and 6th row

# for i in arr12:
#     print(i)

# for i in np.nditer(arr12):      #to print different different element of a matrix
    # print(i)




array([[18, 19],
       [22, 23]])

In [ ]:
import numpy as np
arr1 =np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
arr2-arr1                        #subtract two array
arr1*arr2                       #vector multiplication
arr1*10                         #scalar multiplication
arr1>3             #true where the lement is greater than 3 and otherwise false


arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(12).reshape(3,4)
arr3.dot(arr4)                          #matrix multiplication
arr3.max()                             #give maximum of the matrix
arr3.min()                           #give min of the matrix
arr4.max(axis=0)                    #give the maximum of every column
arr4.min(axis=1)                    #give the minimum of every row
arr4.sum()
arr4.sum(axis=1)                   #sum of all the columns
arr4.sum(axis=0)                    #sum of all the rows
arr4.mean()                          #calculate the mean of the complete data
arr4.std()                          #calculate the standard deviation of the complete data
np.sin(arr4)                        #give sin of all the values of the matrix
np.transpose(arr4)                  #give transpose of the matrix
np.trace(arr4)                    #give trace of the matrix
np.median(arr4)                  #givemedian of the elements of the matrix
np.exp(arr4)                    #give exponent of all the elements of the matrix


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [117]:
arr1 = np.arange(12).reshape(3,4)
arr1
arr1.ndim
arr1.ravel()    #combine the matrix print all the elements in a single row
arr2 = np.arange(12,24).reshape(3,4)
np.hstack((arr1,arr2))                      #combine the two array like connect the all the rows of the matrix
np.vstack((arr1,arr2))                      #combine the two array like connect the all the columns of the matrix
np.vsplit(arr1,3)          #split the matrix horizontally but make sure spliting must be equal to the number of rows
np.hsplit(arr1,4)          #split the matrix vertically but make sure spliting must be equal to the number of columns


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
arr1= np.arange(24).reshape(6,4)
arr1[[0,2,4]]                              #direct access of any row or column of the matrix (called fancy indexing)


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [150]:
#index using boolean arrays
arr1 = np.random.randint(low =10,high =100,size=20).reshape(5,4)
arr1[(arr1)>50]         #only those number is in the output where this condition is true 
# arr1[((arr1)>50) & (arr1%2!=0)]        #two condition on same matrix
# arr1[((arr1)>50) & (arr1%2!=0)] =0
# arr1

array([94, 76, 83, 74, 73, 73, 92, 82, 96, 63], dtype=int32)

In [156]:
import numpy as np
arr1 = np.arange(20).reshape(4,5)
# arr1[d]

In [ ]:
import numpy as np
arr1 = np.linspace(-40,40,101)
arr1.size
arr2 = np.sin(arr1)
arr2.size
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot(arr1,arr2)

101

In [12]:
import numpy as np
arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
arr1+arr2             #do the addition of two matrices
arr1-arr2             #do the subtraction of two matrices
arr1*arr2             #do the multiplication of two matrices
arr1/arr2             #do the division of two matrices


arr3 = np.arange(9).reshape(3,3)
arr4 = np.arange(10,13).reshape(1,3)
arr4+arr3                   #broadcasting of the matrix(adding the row of arr4 to every row of arr3)

arr5= np.arange(20).reshape(5,4)
arr6 = np.arange(5).reshape(5,1)
arr5+arr6 

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [92]:
#Some important functions
import numpy as np
np.random.random()          #generate a random number between 0 and 1
# np.random.seed(1)
np.random.random()
np.random.uniform(3,12)      #if seed is not apply then give the random value between 3 and 11 , values in float
np.random.uniform(1,100,10)  #give array of 10 random values , values in float
np.random.uniform(10,50,20).reshape(4,5)


np.random.randint(1,20,20).reshape(4,5)    #upper function but this time the output will only be integer

x = np.random.randint(1,10,5)
np.max(x)       #gives the maximum element of the array
np.min(x)       #gives the minimum element of the array
np.argmax(x)    #gives the index of the  maximum number of the array
x[np.argmax(x)]   #cross verify by indexing
np.argmin(x)    #gives the index of the  minimum number of the array


arrx = np.random.randint(1,10,5)
#syntax  = (arrx = np.where(condition,true pe value,false pe value))   (where -> don't touch original array)
# arry = np.where(arrx%2 != 0,-1,arrx) #to replace all the odd number of the array with -1.(create a different array)
#arry
arrx[(arrx%2!=0)]=-1                 #alternate method to do the same but this is inplace(don't create a diff. array)
arrx



arr_k = np.random.randint(1,50,10)
arr_y = np.sort(arr_k)                #give different array (not in-place sorting)
np.percentile(arr_y,30)               #30% of my array is coverd upto .
np.percentile(arr_y,60)               #60% of my array covered upto . (means tum itna aage ho -> think like that)
np.percentile(arr_y , 99.9)


np.float64(33.991)

In [ ]:
arr1 = np.arange(20).reshape(4,5)
arr2 = np.flip(arr1[:,2])         # single column flipping
arr2

array([17, 12,  7,  2])